<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário de Recado</title>
    <link rel="stylesheet" href="css/index.css">
</head>
<body>
    <form action="recado.php" method="post">
        <br>
        <input type="text" name="recado" id="recado" placeholder="Recado">
        <br>
        <input type="date" name="data" id="data" placeholder="Data">
        <br>
        <input type="submit" name="btnGerar" id="btnGerar" placeholder="Gerar">
        <br>
          
    </form>
</body>
</html>